### ISSUE TITLE
[8주차] NLP Advanced, Vision Advanced 과제 제출 (~3/12)

### ISSUE THREAD

**Issue by ymnseol** [tobigs-datamarket/tobigs-21st#110]
# Week8. NLP Advanced, Vision Advanced
## Part 1. NLP Advanced

NLP와 관련된 논문을 1개 선정해, 분량, 포맷 제한 없이 리뷰를 작성하여 업로드해주세요!

리뷰에는

- [ ] 논문 내 주요 방법론
- [ ] 논문에서 풀고자 하는 문제
- [ ] 기존의 연구들이 이 문제를 풀어온 방식
- [ ] 기존의 연구 대비 이 논문의 강점
- [ ] 이 논문을 토대로 한 future work에는 무엇이 있을 수 있는지

가 반드시 포함되어야 합니다.

## Part 2. Vision Advanced

Vision Task에 Transformer를 활용한 모델 관련 논문을 하나 선택하여 리뷰 작성하기

- 정규세션 강의자료에 있는 ViT나 Swin Transformer 모델도 좋고,
- 본인이 평소에 알고 싶었던 모델 관련 논문을 선택하셔도 좋습니다.

본인의 블로그나 노션, Word파일, PDF 등 방법은 상관 없습니다.

## 제출 방법
1. 본인의 이름으로 branch를 생성합니다.
2. `main`을 본인의 branch로 pull합니다.
3. **본인의 branch에서** 과제 디렉토리에 본인의 이름으로 디렉토리를 생성합니다.
4. 과제를 수행합니다. 디렉토리 구조:
   ```
   tobigs-21st
   └── Week1
       ├── EDA
       │   └── 김투빅
       │       └── example.md # 과제 파일
       └── Framework
           └── 김투빅
               └── example.md # 과제 파일
   ```
5. 변경된 본인의 branch를 commit, push합니다.
6. `이름(기수) - n주차 과제`라는 타이틀로 `Pull Request`를 등록합니다. 예) 김투빅(21기) - 1주차 과제

## 제출 기한
⏰ ~ 3/12(화) 23:59
