### ISSUE TITLE
[3주차] NB & DT, NN Basic 과제 제출 (~2/6)

### ISSUE THREAD

**Issue by ymnseol** [tobigs-datamarket/tobigs-21st#33]
# Week3. Naïve Bayes Classification & Decision Tree, Neural Network Basic

**원활한 과제 확인을 위해, 반드시 PR naming convention을 지켜주시기 바랍니다!**

## Part 1. Naïve Bayes Classification & Decision Tree
아래 항목들을 반드시 포함하여 과제를 제출해주시기 바랍니다!

### Naïve Bayes Classification

`week3_NaiveBayes_assignment.ipynb` 파일에서,
- [ ] `test_file.xlsx`의 데이터를 활용하여 빈칸 채우기

중간에 서술형으로 써야 하는 항목들은 편하게 아시는 대로 작성하면 됩니다.

### Decision Tree

`week3_DecisionTree_assignment.ipynb` 파일에서,
- [ ] [`https://raw.githubusercontent.com/AugustLONG/ML01/master/01decisiontree/AllElectronics.csv`](https://raw.githubusercontent.com/AugustLONG/ML01/master/01decisiontree/AllElectronics.csv) 의 데이터를 활용하여 빈칸을 채워주세요.

## Part 2. Neural Network Basic

- [ ] `week3_NeuralNetworkBasic_assignment1.pdf` 파일의 문제들을 상세한 풀이과정과 함께 풀기
- [ ] `week3_NeuralNetworkBasic_assignment2.ipynb` 파일에서 코드 실습하기

## 제출 방법
1. 본인의 이름으로 branch를 생성합니다.
2. `main`을 본인의 branch로 pull합니다.
6. **본인의 branch에서** 과제 디렉토리에 본인의 이름으로 디렉토리를 생성합니다.
7. 과제를 수행합니다. 디렉토리 구조:
   ```
   tobigs-21st
   └── Week1
       ├── EDA
       │   └── 김투빅
       │       └── example.md # 과제 파일
       └── Framework
           └── 김투빅
               └── example.md # 과제 파일
   ```
8. 변경된 본인의 branch를 commit, push합니다.
9. `이름(기수) - n주차 과제`라는 타이틀로 `Pull Request`를 등록합니다. 예) 김투빅(21기) - 1주차 과제

## 제출 기한
⏰ ~ 2/6(화) 23:59
