### ISSUE TITLE
[4주차] Ensemble, Dimensionality Reduction 과제 제출 (~2/14)

### ISSUE THREAD

**Issue by ymnseol** [tobigs-datamarket/tobigs-21st#51]
# Week4. Ensemble, Dimensionality Reduction

## Part 1. Ensemble

[Credit Card customers](https://www.kaggle.com/datasets/sakshigoyal7/credit-card-customers) 데이터셋 또는 자신이 원하는 데이터셋을 사용해 앙상블 기법 실습하기 \
⚠️ 위의 데이터셋이 아닌 다른 데이터셋을 사용한 경우, 반드시 원본 데이터셋 링크를 과제에 첨부해주시기 바랍니다.

- [ ] 앙상블 모델 최소 2가지 사용하기
- [ ] 전처리, 모델 성능결과 출력하기

## Part 2. Dimensionality Reduction

`Week4_dimensionality_reduction_assignment.ipynb` 파일에서,

- [ ] MNIST Dataset에 대해 PCA & LDA 적용하기
- [ ] 적용 이전 및 이후 결과(속도 및 성능) 비교하기
- [ ] PCA & LDA 장단점 정리하기

## 제출 방법
1. 본인의 이름으로 branch를 생성합니다.
2. `main`을 본인의 branch로 pull합니다.
3. **본인의 branch에서** 과제 디렉토리에 본인의 이름으로 디렉토리를 생성합니다.
4. 과제를 수행합니다. 디렉토리 구조:
   ```
   tobigs-21st
   └── Week1
       ├── EDA
       │   └── 김투빅
       │       └── example.md # 과제 파일
       └── Framework
           └── 김투빅
               └── example.md # 과제 파일
   ```
5. 변경된 본인의 branch를 commit, push합니다.
6. `이름(기수) - n주차 과제`라는 타이틀로 `Pull Request`를 등록합니다. 예) 김투빅(21기) - 1주차 과제

## 제출 기한
⏰ ~ 2/14(화) 23:59
